name: kitty_burger_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dropdown_button2: ^1.7.2
  sqflite: ^2.0.3+1
  path_provider: ^2.0.9
  path: ^1.8.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  http: ^0.13.5
  dio: ^4.0.4
  get: ^4.6.5
  plugin_platform_interface: ^2.1.3
  external_path: ^1.0.3
  geolocator: ^9.0.2
  flutter_session_manager: ^1.0.3
  future_progress_dialog: ^0.2.0
  flutter_launcher_icons: ^0.11.0
  camera: ^0.10.3
  image_picker: ^0.8.6+1
  image: ^3.0.2
  group_radio_button: ^1.3.0
  permission_handler: ^10.2.0
  stamp_image: ^0.0.2
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.10
  flutter_linkify: ^5.0.2
  file_picker: ^5.2.10
  flutter_windowmanager: ^0.2.0
  carousel_slider: ^4.2.1
  flutter_otp_text_field: ^1.1.1
  persistent_shopping_cart: ^0.0.7
  cached_network_image: ^3.3.1
  flutter_cart: ^0.0.9
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.1
  card_banner: ^0.0.1+2
  no_internet_connection_widget: ^1.0.1
  connectivity: ^3.0.6
  syncfusion_flutter_datagrid: ^25.2.6

flutter_icons:
  android: true
  ios: true
  image_path: "lib/database/kittyBurger_logo.jpg"
  flutter_dynamic_icon: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/database/kittyBurger_logo.jpg
    - lib/database/ktylogo.jpg
    - lib/database/kittyburgerlogo.jpg

  uses-material-design: true
